name: AnhTuan201X Bot Auto Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev bzip2 unzip

      - name: Run Package Builder Script
        run: |
          chmod +x sync.sh
          ./sync.sh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "anhtuan201x-bot"
          git config --global user.email "anhtuan201x@github.io"
          git add -A
          if ! git diff --cached --exit-code --quiet; then
            git commit -m "Bot: Auto updated Cydia Repo & IPA Store"
            # LỆNH THẦN THÁNH ÉP ĐỒNG BỘ GỘP NHÁNH PHÁ CACHE LỆCH LỊCH SỬ
            git pull origin main --rebase --strategy-option=theirs || true
            git push origin main
          else
            echo "No changes detected. Skipping push."
          fi
